/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/exports/{export_id}": {
    /** Get Export */
    get: operations["QI-API-EXP-002"];
  };
  "/api/v1/exports/{export_id}/downloads/{kind}": {
    /** Download Export */
    get: operations["QI-API-EXP-003"];
  };
  "/api/v1/health": {
    /** Health */
    get: operations["QI-API-SYS-001"];
  };
  "/api/v1/projects": {
    /** Create Project */
    post: operations["QI-API-PRJ-001"];
  };
  "/api/v1/projects/{project_id}/balloons": {
    /** List Balloons */
    get: operations["QI-API-BAL-001"];
  };
  "/api/v1/projects/{project_id}/balloons/commands": {
    /** Apply Balloon Command */
    post: operations["QI-API-BAL-003"];
  };
  "/api/v1/projects/{project_id}/balloons/generate": {
    /** Generate Balloons */
    post: operations["QI-API-BAL-002"];
  };
  "/api/v1/projects/{project_id}/exports": {
    /** Create Export */
    post: operations["QI-API-EXP-001"];
  };
  "/api/v1/projects/{project_id}/recognition-preview": {
    /** Get Recognition Preview */
    get: operations["QI-API-PRJ-005"];
  };
  "/api/v1/projects/{project_id}/review/commands": {
    /** Apply Command */
    post: operations["QI-API-REV-003"];
  };
  "/api/v1/projects/{project_id}/review/confirm": {
    /** Confirm Review */
    post: operations["QI-API-REV-005"];
  };
  "/api/v1/projects/{project_id}/review/freeze-items": {
    /** Freeze Items */
    post: operations["QI-API-REV-004"];
  };
  "/api/v1/projects/{project_id}/review/lock": {
    /** Lock Review */
    post: operations["QI-API-REV-001"];
  };
  "/api/v1/projects/{project_id}/review/working-copy": {
    /** Get Working Copy */
    get: operations["QI-API-REV-002"];
  };
  "/api/v1/projects/{project_id}/source-pdf": {
    /** Get Source Pdf */
    get: operations["QI-API-PRJ-004"];
  };
  "/api/v1/projects/{project_id}/status": {
    /** Get Project Status */
    get: operations["QI-API-PRJ-002"];
  };
  "/api/v1/projects/{project_id}/workbench": {
    /** Get Workbench */
    get: operations["QI-API-PRJ-003"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Add */
    Add: {
      /** Balloon Required */
      balloon_required: boolean;
      /** Coordinates */
      coordinates: [number, number, number, number];
      /**
       * Item Type
       * @enum {string}
       */
      item_type: "linear_dimension" | "diameter_dimension" | "thread" | "radius" | "angle" | "general_requirement" | "composite";
      /** Page Index */
      page_index?: number | null;
      /** Raw Text */
      raw_text: string;
      /**
       * Scope
       * @enum {string}
       */
      scope: "local_feature" | "global_requirement";
      /**
       * Type
       * @constant
       */
      type: "add";
    };
    /** BalloonCollectionResponse */
    BalloonCollectionResponse: {
      /** Balloons */
      balloons: components["schemas"]["BalloonResponse"][];
    };
    /** BalloonResponse */
    BalloonResponse: {
      /** Anchor Bbox Pdf */
      anchor_bbox_pdf: [number, number, number, number];
      /** Center Pdf */
      center_pdf: [number, number];
      /** Collision Flags */
      collision_flags: ("circle_overlap" | "glyph_overlap" | "glyph_circle_overlap" | "owner_glyph_outside_circle" | "outside_cropbox" | "protected_overlap" | "source_text_overlap" | "unreadable_number" | "invalid_leader" | "forbidden_overlap")[];
      /** Formal Number */
      formal_number: number | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Inspection Item Id */
      inspection_item_id: string;
      /** Leader Target Pdf */
      leader_target_pdf: [number, number];
      /** Page Index */
      page_index: number;
      /**
       * Placement Status
       * @enum {string}
       */
      placement_status: "placed" | "manual_required";
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Sort Order */
      sort_order: number;
      /** Source Location Id */
      source_location_id: string;
      /**
       * Status
       * @enum {string}
       */
      status: "active" | "deleted";
      /** Suggested Number */
      suggested_number: number;
      /** Version */
      version: number;
    };
    /** Body_QI-API-PRJ-001 */
    "Body_QI-API-PRJ-001": {
      /** File */
      file: string;
    };
    /** CoarseReviewItem */
    CoarseReviewItem: {
      /** Acceptance Source */
      acceptance_source?: string | null;
      /**
       * Active
       * @default true
       */
      active?: boolean;
      /** Balloon Required */
      balloon_required?: boolean | null;
      /**
       * Coarse Type
       * @enum {string}
       */
      coarse_type: "roughness" | "weld" | "cross_view_duplicate";
      /** Confidence Decision */
      confidence_decision?: {
        [key: string]: unknown;
      } | null;
      /** Confirmation Accepted */
      confirmation_accepted?: boolean | null;
      /** Coordinates */
      coordinates?: [number, number, number, number] | null;
      /** Inspection Item */
      inspection_item?: string | null;
      /** Inspection Method */
      inspection_method?: string | null;
      /** Inspection Role */
      inspection_role?: string | null;
      /** Inspection Standard */
      inspection_standard?: string | null;
      /** Item Id */
      item_id: string;
      /** Key Dimension */
      key_dimension?: string | null;
      /** Merged From Item Ids */
      merged_from_item_ids?: string[] | null;
      /** Normalized Text */
      normalized_text?: string | null;
      /** Page Index */
      page_index?: number | null;
      /** Raw Text */
      raw_text: string;
      /** Remarks */
      remarks?: string | null;
      /** Requires Confirmation */
      requires_confirmation: boolean;
      /** Scope */
      scope?: ("local_feature" | "global_requirement") | null;
      /** Sip Detail Fields Confirmed */
      sip_detail_fields_confirmed?: boolean | null;
      /** Sip Mapping Exceptions */
      sip_mapping_exceptions?: string[] | null;
      /** Sip Suggestion Provenance */
      sip_suggestion_provenance?: {
        [key: string]: string;
      } | null;
      /** Source Location Ids */
      source_location_ids: string[];
      /** Source Page */
      source_page?: number | null;
      /**
       * Source Type
       * @enum {string}
       */
      source_type: "automatic" | "manual";
      /** Split From Item Id */
      split_from_item_id?: string | null;
      /** Status */
      status: string;
      /** Technical Requirement Refs */
      technical_requirement_refs?: string[] | null;
    };
    /** ConfirmReviewRequest */
    ConfirmReviewRequest: {
      /** Expected Version */
      expected_version: number;
    };
    /** CreateExportRequest */
    CreateExportRequest: {
      /**
       * Reviewed Result Id
       * Format: uuid
       */
      reviewed_result_id: string;
    };
    /** DeleteBalloon */
    DeleteBalloon: {
      /**
       * Balloon Id
       * Format: uuid
       */
      balloon_id: string;
      /** Expected Version */
      expected_version: number;
      /**
       * Type
       * @constant
       */
      type: "delete";
    };
    /** Edit */
    Edit: {
      /** Fields */
      fields: {
        [key: string]: unknown;
      };
      /** Item Id */
      item_id: string;
      /**
       * Type
       * @constant
       */
      type: "edit";
    };
    /** ErrorDetail */
    ErrorDetail: {
      /** Blockers */
      blockers?: string[] | null;
      /** Cause Category */
      cause_category: string;
      /** Code */
      code: string;
      /** Location Ref */
      location_ref: string | null;
      /** Message */
      message: string;
      /** Phase */
      phase?: string | null;
      /** Project Id */
      project_id?: string | null;
      /** Retryable */
      retryable?: boolean | null;
      /**
       * Severity
       * @enum {string}
       */
      severity: "fatal" | "blocking" | "review_required" | "warning" | "informational";
      /** Stage */
      stage: string;
      /** Workbench Ready */
      workbench_ready?: boolean | null;
    };
    /** ErrorEnvelope */
    ErrorEnvelope: {
      error: components["schemas"]["ErrorDetail"];
    };
    /** Exclude */
    Exclude: {
      /** Item Id */
      item_id: string;
      /**
       * Type
       * @constant
       */
      type: "exclude";
    };
    /** ExportArtifactResponse */
    ExportArtifactResponse: {
      /** Downloadable */
      downloadable: boolean;
      /**
       * Kind
       * @enum {string}
       */
      kind: "ballooned_pdf" | "sip_excel" | "manifest";
      /**
       * Reviewed Result Id
       * Format: uuid
       */
      reviewed_result_id: string;
      /** Sha256 */
      sha256: string;
      /** Size Bytes */
      size_bytes: number;
    };
    /** ExportResponse */
    ExportResponse: {
      /** Artifacts */
      artifacts: components["schemas"]["ExportArtifactResponse"][];
      /** Error Id */
      error_id: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Mapping Version */
      mapping_version: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Renderer Version */
      renderer_version: string;
      /**
       * Reviewed Result Id
       * Format: uuid
       */
      reviewed_result_id: string;
      /**
       * Status
       * @enum {string}
       */
      status: "running" | "success" | "failed";
      /** Template Version */
      template_version: string;
    };
    /** FreezeItemsRequest */
    FreezeItemsRequest: {
      /** Expected Version */
      expected_version: number;
    };
    /** GenerateBalloonsRequest */
    GenerateBalloonsRequest: {
      /** Expected Version */
      expected_version: number;
    };
    /** GenerateSipTable */
    GenerateSipTable: {
      /** Inspection Role */
      inspection_role: string;
      /**
       * Type
       * @constant
       */
      type: "generate_sip_table";
    };
    /** GeometricToleranceReviewDatumReference */
    GeometricToleranceReviewDatumReference: {
      /** Datum */
      datum: string;
      /** Modifiers */
      modifiers?: components["schemas"]["GeometricToleranceReviewModifier"][];
    };
    /** GeometricToleranceReviewFrame */
    GeometricToleranceReviewFrame: {
      /** Segments */
      segments: components["schemas"]["GeometricToleranceReviewSegment"][];
    };
    /** GeometricToleranceReviewItem */
    GeometricToleranceReviewItem: {
      /** Acceptance Source */
      acceptance_source?: string | null;
      /**
       * Active
       * @default true
       */
      active?: boolean;
      /** Balloon Required */
      balloon_required?: boolean | null;
      /** Confidence Decision */
      confidence_decision?: {
        [key: string]: unknown;
      } | null;
      /** Confirmation Accepted */
      confirmation_accepted?: boolean | null;
      /** Coordinates */
      coordinates: [number, number, number, number];
      /** Datum References */
      datum_references: components["schemas"]["GeometricToleranceReviewDatumReference"][];
      /** Diameter Modifier */
      diameter_modifier: boolean;
      /** Evidence Ref */
      evidence_ref: string;
      /** Frames */
      frames: components["schemas"]["GeometricToleranceReviewFrame"][];
      /** Inspection Item */
      inspection_item?: string | null;
      /** Inspection Method */
      inspection_method?: string | null;
      /** Inspection Role */
      inspection_role?: string | null;
      /** Inspection Standard */
      inspection_standard?: string | null;
      /** Item Id */
      item_id: string;
      /**
       * Item Type
       * @constant
       */
      item_type: "geometric_tolerance";
      /** Key Dimension */
      key_dimension?: string | null;
      /** Merged From Item Ids */
      merged_from_item_ids?: string[] | null;
      /** Modifiers */
      modifiers: components["schemas"]["GeometricToleranceReviewModifier"][];
      /** Normalized Text */
      normalized_text: string;
      /** Page Index */
      page_index?: number | null;
      /** Raw Text */
      raw_text: string;
      /** Remarks */
      remarks?: string | null;
      /** Requires Confirmation */
      requires_confirmation: boolean;
      /**
       * Schema Version
       * @constant
       */
      schema_version: "geometric-tolerance-candidate/1";
      /** Scope */
      scope?: ("local_feature" | "global_requirement") | null;
      /** Sip Detail Fields Confirmed */
      sip_detail_fields_confirmed?: boolean | null;
      /** Sip Mapping Exceptions */
      sip_mapping_exceptions?: string[] | null;
      /** Sip Suggestion Provenance */
      sip_suggestion_provenance?: {
        [key: string]: string;
      } | null;
      /** Source Location Ids */
      source_location_ids: string[];
      /** Source Page */
      source_page?: number | null;
      /**
       * Source Type
       * @enum {string}
       */
      source_type: "automatic" | "manual";
      /** Split From Item Id */
      split_from_item_id?: string | null;
      /**
       * Standard Context
       * @constant
       */
      standard_context: "unspecified";
      /** Status */
      status: string;
      /** Technical Requirement Refs */
      technical_requirement_refs?: string[] | null;
      /** Tolerance Symbol */
      tolerance_symbol: string | null;
      /**
       * Tolerance Type
       * @enum {string}
       */
      tolerance_type: "straightness" | "flatness" | "circularity" | "cylindricity" | "profile_of_line" | "profile_of_surface" | "angularity" | "perpendicularity" | "parallelism" | "position" | "concentricity_or_coaxiality" | "symmetry" | "circular_runout" | "total_runout" | "unknown";
      /** Tolerance Value */
      tolerance_value: string | null;
    };
    /** GeometricToleranceReviewModifier */
    GeometricToleranceReviewModifier: {
      /**
       * Kind
       * @enum {string}
       */
      kind: "maximum_material_condition" | "least_material_condition" | "regardless_of_feature_size" | "unknown";
      /** Raw Symbol */
      raw_symbol: string;
    };
    /** GeometricToleranceReviewSegment */
    GeometricToleranceReviewSegment: {
      /** Datum References */
      datum_references: components["schemas"]["GeometricToleranceReviewDatumReference"][];
      /** Diameter Modifier */
      diameter_modifier: boolean;
      /** Modifiers */
      modifiers: components["schemas"]["GeometricToleranceReviewModifier"][];
      /** Tolerance Value */
      tolerance_value: string;
    };
    /** HealthResponse */
    HealthResponse: {
      /** App Name */
      app_name: string;
      /** Status */
      status: string;
    };
    /** IgnoreSource */
    IgnoreSource: {
      /** Observation Id */
      observation_id: string;
      /**
       * Type
       * @constant
       */
      type: "ignore_source";
    };
    /** IgnoreSources */
    IgnoreSources: {
      /** Observation Ids */
      observation_ids: string[];
      /**
       * Type
       * @constant
       */
      type: "ignore_sources";
    };
    /** Keep */
    Keep: {
      /** Item Id */
      item_id: string;
      /**
       * Type
       * @constant
       */
      type: "keep";
    };
    /** LockRequest */
    LockRequest: {
      /**
       * Ttl Seconds
       * @default 300
       */
      ttl_seconds?: number;
    };
    /** Merge */
    Merge: {
      /** Item Ids */
      item_ids: string[];
      /** Raw Text */
      raw_text: string;
      /**
       * Type
       * @constant
       */
      type: "merge";
    };
    /** MoveBalloon */
    MoveBalloon: {
      /**
       * Balloon Id
       * Format: uuid
       */
      balloon_id: string;
      /** Center Pdf */
      center_pdf: [number, number];
      /** Expected Version */
      expected_version: number;
      /**
       * Type
       * @constant
       */
      type: "move";
    };
    /**
     * ProcessingStage
     * @enum {string}
     */
    ProcessingStage: "queued" | "parsing" | "recognizing" | "local_ready" | "vlm_enriching" | "preparing_review";
    /** ProjectError */
    ProjectError: {
      /** Code */
      code: string;
      /** Stage */
      stage: string;
    };
    /**
     * ProjectPhase
     * @enum {string}
     */
    ProjectPhase: "queued" | "processing" | "ready_for_review" | "partial_review_required" | "failed";
    /**
     * ProjectState
     * @enum {string}
     */
    ProjectState: "processing" | "ready_for_edit" | "editing" | "reviewed" | "exporting" | "export_succeeded" | "processing_failed" | "export_failed" | "unsupported_input";
    /** ProjectStatusResponse */
    ProjectStatusResponse: {
      error: components["schemas"]["ProjectError"] | null;
      phase: components["schemas"]["ProjectPhase"];
      /** Project Id */
      project_id?: string | null;
      /** Retryable */
      retryable: boolean;
      stage?: components["schemas"]["ProcessingStage"] | null;
      /** Workbench Ready */
      workbench_ready: boolean;
    };
    /** ProjectWorkbenchCandidateResponse */
    ProjectWorkbenchCandidateResponse: {
      /** Bbox Pdf */
      bbox_pdf: [number, number, number, number];
      /** Confidence Band */
      confidence_band: ("high" | "medium" | "low") | null;
      /** Id */
      id: string;
      /** Item Id */
      item_id: string;
      /** Page Index */
      page_index: number;
      /** Review Disposition */
      review_disposition: ("auto_accepted" | "review_required") | null;
      /** Status */
      status: string | null;
    };
    /** ProjectWorkbenchPageResponse */
    ProjectWorkbenchPageResponse: {
      /** Height */
      height: number;
      /** Page Index */
      page_index: number;
      /** Pdf To Render Matrix */
      pdf_to_render_matrix: [number, number, number, number, number, number];
      /** Render To Pdf Matrix */
      render_to_pdf_matrix: [number, number, number, number, number, number];
      /** Width */
      width: number;
    };
    /** ProjectWorkbenchResponse */
    ProjectWorkbenchResponse: {
      /** Balloon Blockers */
      balloon_blockers: string[];
      /** Balloons */
      balloons: components["schemas"]["BalloonResponse"][];
      /** Candidates */
      candidates: components["schemas"]["ProjectWorkbenchCandidateResponse"][];
      latest_export: components["schemas"]["ExportResponse"] | null;
      /** Pages */
      pages: components["schemas"]["ProjectWorkbenchPageResponse"][];
      project: components["schemas"]["WorkbenchProjectResponse"];
      /** Reviewed Result Id */
      reviewed_result_id: string | null;
      /** Sip Metadata Suggestions */
      sip_metadata_suggestions: components["schemas"]["ProjectWorkbenchSipMetadataSuggestionResponse"][];
      /** Source Pdf Url */
      source_pdf_url: string;
      /** Sources */
      sources: components["schemas"]["ProjectWorkbenchSourceResponse"][];
      working_copy: components["schemas"]["ReviewWorkingCopyProjection"];
    };
    /** ProjectWorkbenchSipMetadataSuggestionResponse */
    ProjectWorkbenchSipMetadataSuggestionResponse: {
      /** Bbox Pdf */
      bbox_pdf: [number, number, number, number];
      /** Evidence Codes */
      evidence_codes: string[];
      /**
       * Field
       * @enum {string}
       */
      field: "material_code" | "material_name" | "drawing_number" | "material" | "revision";
      /** Label Observation Id */
      label_observation_id: string | null;
      /** Observation Id */
      observation_id: string;
      /** Page Index */
      page_index: number;
      /**
       * Rule Version
       * @constant
       */
      rule_version: "welli-title-metadata/1";
      /** Value */
      value: string;
    };
    /** ProjectWorkbenchSourceResponse */
    ProjectWorkbenchSourceResponse: {
      /** Bbox Pdf */
      bbox_pdf: [number, number, number, number];
      /** Id */
      id: string;
      /** Item Ids */
      item_ids: string[];
      /** Page Index */
      page_index: number;
      /** Raw Text */
      raw_text: string;
      /**
       * Source Type
       * @enum {string}
       */
      source_type: "text" | "visual";
    };
    /** PromoteSource */
    PromoteSource: {
      /** Balloon Required */
      balloon_required: boolean;
      /**
       * Item Type
       * @enum {string}
       */
      item_type: "linear_dimension" | "diameter_dimension" | "thread" | "radius" | "angle" | "general_requirement" | "composite";
      /** Observation Id */
      observation_id: string;
      /** Page Index */
      page_index: number;
      /** Raw Text */
      raw_text: string;
      /**
       * Scope
       * @enum {string}
       */
      scope: "local_feature" | "global_requirement";
      /**
       * Type
       * @constant
       */
      type: "promote_source";
    };
    /** RebuildBalloon */
    RebuildBalloon: {
      /**
       * Balloon Id
       * Format: uuid
       */
      balloon_id: string;
      /** Expected Version */
      expected_version: number;
      /**
       * Type
       * @constant
       */
      type: "rebuild";
    };
    /** RecognitionPreviewCandidate */
    RecognitionPreviewCandidate: {
      /** Candidate Id */
      candidate_id: string;
      /** Kind */
      kind: string;
      /** Label */
      label: string;
    };
    /** RecognitionPreviewCounts */
    RecognitionPreviewCounts: {
      /** Cache Resolved */
      cache_resolved: number;
      /** Local Resolved */
      local_resolved: number;
      /** Unresolved */
      unresolved: number;
      /** Vlm Pending */
      vlm_pending: number;
      /** Vlm Resolved */
      vlm_resolved: number;
    };
    /** RecognitionPreviewResponse */
    RecognitionPreviewResponse: {
      counts: components["schemas"]["RecognitionPreviewCounts"];
      /** Revision */
      revision: number;
      semantic_snapshot: components["schemas"]["RecognitionPreviewSnapshot"];
      /** Source Pdf Url */
      source_pdf_url: string;
      /**
       * Stage
       * @enum {string}
       */
      stage: "local_ready" | "vlm_enriching";
    };
    /** RecognitionPreviewSnapshot */
    RecognitionPreviewSnapshot: {
      /** Candidates */
      candidates: components["schemas"]["RecognitionPreviewCandidate"][];
      counts: components["schemas"]["RecognitionPreviewCounts"];
      /**
       * Schema Version
       * @constant
       */
      schema_version: "recognition-preview/1";
      /** Sources */
      sources: components["schemas"]["RecognitionPreviewSource"][];
      /**
       * Stage
       * @enum {string}
       */
      stage: "local_ready" | "vlm_enriching";
    };
    /** RecognitionPreviewSource */
    RecognitionPreviewSource: {
      /** Page Index */
      page_index: number;
      /** Raw Text */
      raw_text: string;
      /** Source Location Id */
      source_location_id: string;
      /** Source Type */
      source_type: string;
    };
    /** RenumberBalloons */
    RenumberBalloons: {
      /** Expected Versions */
      expected_versions: {
        [key: string]: number;
      };
      /** Ordered Balloon Ids */
      ordered_balloon_ids: string[];
      /**
       * Type
       * @constant
       */
      type: "renumber";
    };
    /** ReorderBalloon */
    ReorderBalloon: {
      /**
       * Balloon Id
       * Format: uuid
       */
      balloon_id: string;
      /** Expected Version */
      expected_version: number;
      /** Sort Order */
      sort_order: number;
      /**
       * Type
       * @constant
       */
      type: "reorder";
    };
    /** ResolveConfirmation */
    ResolveConfirmation: {
      /** Accepted */
      accepted: boolean;
      /** Item Id */
      item_id: string;
      /**
       * Type
       * @constant
       */
      type: "resolve_confirmation";
    };
    /** ReviewCommandRequest */
    ReviewCommandRequest: {
      /** Command */
      command: components["schemas"]["Keep"] | components["schemas"]["Exclude"] | components["schemas"]["Edit"] | components["schemas"]["Add"] | components["schemas"]["PromoteSource"] | components["schemas"]["IgnoreSource"] | components["schemas"]["IgnoreSources"] | components["schemas"]["Merge"] | components["schemas"]["Split"] | components["schemas"]["ResolveConfirmation"] | components["schemas"]["SetBalloonRequired"] | components["schemas"]["SetSipDetailFields"] | components["schemas"]["GenerateSipTable"] | components["schemas"]["SetSipMetadata"] | components["schemas"]["SetTechnicalRequirementMatch"];
      /** Expected Version */
      expected_version: number;
    };
    /** ReviewLockResponse */
    ReviewLockResponse: {
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /** Operator Id */
      operator_id: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
    };
    /** ReviewWorkingCopyProjection */
    ReviewWorkingCopyProjection: {
      /** Coverage */
      coverage: {
        [key: string]: unknown;
      };
      /** Created At */
      created_at?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Items */
      items: (components["schemas"]["GeometricToleranceReviewItem"] | components["schemas"]["TypedReviewItem"] | components["schemas"]["CoarseReviewItem"])[];
      /** Items Frozen At */
      items_frozen_at: string | null;
      /** Items Frozen By */
      items_frozen_by: string | null;
      /** Items Frozen Version */
      items_frozen_version: number | null;
      /** Manual Review Count */
      manual_review_count: number;
      /** Numbering Stale */
      numbering_stale: boolean;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /**
       * Raw Result Id
       * Format: uuid
       */
      raw_result_id: string;
      /** Sip Metadata */
      sip_metadata: {
        [key: string]: unknown;
      };
      /** Technical Requirements */
      technical_requirements: {
          [key: string]: unknown;
        }[];
      /** Updated At */
      updated_at?: string | null;
      /** Version */
      version: number;
    };
    /** ReviewWorkingCopyResponse */
    ReviewWorkingCopyResponse: {
      /** Coverage */
      coverage: {
        [key: string]: unknown;
      };
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Items */
      items: (components["schemas"]["GeometricToleranceReviewItem"] | components["schemas"]["TypedReviewItem"] | components["schemas"]["CoarseReviewItem"])[];
      /** Items Frozen At */
      items_frozen_at: string | null;
      /** Items Frozen By */
      items_frozen_by: string | null;
      /** Items Frozen Version */
      items_frozen_version: number | null;
      /** Manual Review Count */
      manual_review_count: number;
      /** Numbering Stale */
      numbering_stale: boolean;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /**
       * Raw Result Id
       * Format: uuid
       */
      raw_result_id: string;
      /** Sip Metadata */
      sip_metadata: {
        [key: string]: unknown;
      };
      /** Technical Requirements */
      technical_requirements: {
          [key: string]: unknown;
        }[];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Version */
      version: number;
    };
    /** ReviewedResultResponse */
    ReviewedResultResponse: {
      /** Balloons */
      balloons: {
          [key: string]: unknown;
        }[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Items */
      items: (components["schemas"]["GeometricToleranceReviewItem"] | components["schemas"]["TypedReviewItem"] | components["schemas"]["CoarseReviewItem"])[];
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Schema Version */
      schema_version: string;
      /** Sip Metadata */
      sip_metadata: {
        [key: string]: unknown;
      };
      /**
       * Working Copy Id
       * Format: uuid
       */
      working_copy_id: string;
      /** Working Version */
      working_version: number;
    };
    /** SetBalloonRequired */
    SetBalloonRequired: {
      /** Balloon Required */
      balloon_required: boolean;
      /** Item Id */
      item_id: string;
      /**
       * Type
       * @constant
       */
      type: "set_balloon_required";
    };
    /** SetSipDetailFields */
    SetSipDetailFields: {
      /** Inspection Item */
      inspection_item: string;
      /** Inspection Method */
      inspection_method: string;
      /** Inspection Role */
      inspection_role: string;
      /** Inspection Standard */
      inspection_standard: string;
      /** Item Id */
      item_id: string;
      /** Key Dimension */
      key_dimension: string;
      /**
       * Remarks
       * @default
       */
      remarks?: string;
      /** Source Page */
      source_page: number;
      /**
       * Type
       * @constant
       */
      type: "set_sip_detail_fields";
    };
    /** SetSipMetadata */
    SetSipMetadata: {
      /** Drawing Number */
      drawing_number: string;
      /** Material */
      material: string;
      /** Material Code */
      material_code: string;
      /** Material Name */
      material_name: string;
      /** Revision */
      revision: string;
      /**
       * Type
       * @constant
       */
      type: "set_sip_metadata";
    };
    /** SetTechnicalRequirementMatch */
    SetTechnicalRequirementMatch: {
      /** Matched Item Ids */
      matched_item_ids?: string[];
      /**
       * Outcome
       * @enum {string}
       */
      outcome: "matched_items" | "global_scope" | "excluded";
      /** Requirement Id */
      requirement_id: string;
      /**
       * Type
       * @constant
       */
      type: "set_technical_requirement_match";
    };
    /** Split */
    Split: {
      /** Item Id */
      item_id: string;
      /** Parts */
      parts: components["schemas"]["SplitPart"][];
      /**
       * Type
       * @constant
       */
      type: "split";
    };
    /** SplitPart */
    SplitPart: {
      /** Raw Text */
      raw_text: string;
    };
    /** TypedReviewItem */
    TypedReviewItem: {
      /** Acceptance Source */
      acceptance_source?: string | null;
      /**
       * Active
       * @default true
       */
      active?: boolean;
      /** Angle Value */
      angle_value?: string | null;
      /** Balloon Required */
      balloon_required?: boolean | null;
      /** Confidence Decision */
      confidence_decision?: {
        [key: string]: unknown;
      } | null;
      /** Confirmation Accepted */
      confirmation_accepted?: boolean | null;
      /** Coordinates */
      coordinates?: [number, number, number, number] | null;
      /** Depth */
      depth?: string | null;
      /** Feature Kind */
      feature_kind?: ("hole" | "shaft" | "cylindrical_feature" | "unknown") | null;
      /** Inspection Item */
      inspection_item?: string | null;
      /** Inspection Method */
      inspection_method?: string | null;
      /** Inspection Role */
      inspection_role?: string | null;
      /** Inspection Standard */
      inspection_standard?: string | null;
      /** Item Id */
      item_id: string;
      /**
       * Item Type
       * @enum {string}
       */
      item_type: "linear_dimension" | "diameter_dimension" | "thread" | "radius" | "angle" | "general_requirement" | "composite";
      /** Key Dimension */
      key_dimension?: string | null;
      /** Lower Tolerance */
      lower_tolerance?: string | null;
      /** Merged From Item Ids */
      merged_from_item_ids?: string[] | null;
      /** Nominal */
      nominal?: string | null;
      /** Normalized Text */
      normalized_text?: string | null;
      /** Page Index */
      page_index?: number | null;
      /** Quantity */
      quantity?: number | null;
      /** Radius Value */
      radius_value?: string | null;
      /** Raw Text */
      raw_text: string;
      /** Remarks */
      remarks?: string | null;
      /** Requires Confirmation */
      requires_confirmation: boolean;
      /** Scope */
      scope?: ("local_feature" | "global_requirement") | null;
      /** Sip Detail Fields Confirmed */
      sip_detail_fields_confirmed?: boolean | null;
      /** Sip Mapping Exceptions */
      sip_mapping_exceptions?: string[] | null;
      /** Sip Suggestion Provenance */
      sip_suggestion_provenance?: {
        [key: string]: string;
      } | null;
      /** Source Location Ids */
      source_location_ids: string[];
      /** Source Page */
      source_page?: number | null;
      /**
       * Source Type
       * @enum {string}
       */
      source_type: "automatic" | "manual";
      /** Split From Item Id */
      split_from_item_id?: string | null;
      /** Status */
      status: string;
      /** Sub Requirements */
      sub_requirements?: {
          [key: string]: unknown;
        }[];
      /** Technical Requirement Refs */
      technical_requirement_refs?: string[] | null;
      /** Thread Depth */
      thread_depth?: string | null;
      /** Thread Spec */
      thread_spec?: string | null;
      /** Through */
      through?: boolean | null;
      /** Upper Tolerance */
      upper_tolerance?: string | null;
    };
    /** WorkbenchProjectResponse */
    WorkbenchProjectResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      state: components["schemas"]["ProjectState"];
      /** Version */
      version: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get Export */
  "QI-API-EXP-002": {
    parameters: {
      path: {
        export_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ExportResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Download Export */
  "QI-API-EXP-003": {
    parameters: {
      path: {
        export_id: string;
        kind: string;
      };
    };
    responses: {
      /** @description Published export artifact. */
      200: {
        content: {
          "application/json": string;
          "application/pdf": string;
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request conflicts with current aggregate or capability state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Health */
  "QI-API-SYS-001": {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Create Project */
  "QI-API-PRJ-001": {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_QI-API-PRJ-001"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        content: {
          "application/json": components["schemas"]["ProjectStatusResponse"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Required dispatch or service is unavailable. */
      503: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** List Balloons */
  "QI-API-BAL-001": {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BalloonCollectionResponse"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Apply Balloon Command */
  "QI-API-BAL-003": {
    parameters: {
      header: {
        "X-QI-Operator": string;
      };
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MoveBalloon"] | components["schemas"]["DeleteBalloon"] | components["schemas"]["RebuildBalloon"] | components["schemas"]["ReorderBalloon"] | components["schemas"]["RenumberBalloons"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BalloonResponse"] | components["schemas"]["BalloonCollectionResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request conflicts with current aggregate or capability state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Generate Balloons */
  "QI-API-BAL-002": {
    parameters: {
      header: {
        "X-QI-Operator": string;
      };
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateBalloonsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["BalloonCollectionResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request conflicts with current aggregate or capability state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Create Export */
  "QI-API-EXP-001": {
    parameters: {
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateExportRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ExportResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request conflicts with current aggregate or capability state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Get Recognition Preview */
  "QI-API-PRJ-005": {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RecognitionPreviewResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request conflicts with current aggregate or capability state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Apply Command */
  "QI-API-REV-003": {
    parameters: {
      header: {
        "X-QI-Operator": string;
      };
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReviewCommandRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReviewWorkingCopyResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request conflicts with current aggregate or capability state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Confirm Review */
  "QI-API-REV-005": {
    parameters: {
      header: {
        "X-QI-Operator": string;
      };
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmReviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReviewedResultResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request conflicts with current aggregate or capability state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Freeze Items */
  "QI-API-REV-004": {
    parameters: {
      header: {
        "X-QI-Operator": string;
      };
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FreezeItemsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReviewWorkingCopyResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request conflicts with current aggregate or capability state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Lock Review */
  "QI-API-REV-001": {
    parameters: {
      header: {
        "X-QI-Operator": string;
      };
      path: {
        project_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LockRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReviewLockResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request conflicts with current aggregate or capability state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Get Working Copy */
  "QI-API-REV-002": {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReviewWorkingCopyResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Get Source Pdf */
  "QI-API-PRJ-004": {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Original project PDF. */
      200: {
        content: {
          "application/pdf": string;
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request conflicts with current aggregate or capability state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Get Project Status */
  "QI-API-PRJ-002": {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectStatusResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  /** Get Workbench */
  "QI-API-PRJ-003": {
    parameters: {
      path: {
        project_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ProjectWorkbenchResponse"];
        };
      };
      /** @description Requested resource was not found. */
      404: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request conflicts with current aggregate or capability state. */
      409: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Request failed transport or business validation. */
      422: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unexpected internal failure. */
      500: {
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
}
