const ERROR_COPY: Readonly<Record<string, string>> = {
  invalid_pdf: "PDF 格式错误，请选择有效的工程 PDF。",
  unsupported_input: "当前 PDF 暂不支持。",
  storage_unavailable: "文件存储服务暂不可用，请稍后重试。",
  redis_unavailable: "处理协调服务暂不可用，请稍后重试。",
  celery_worker_unavailable: "图纸处理服务暂不可用，请稍后重试。",
  ocr_provider_unavailable: "文字识别服务暂不可用，请稍后重试。",
  vision_provider_unavailable: "图纸识别服务暂不可用，请稍后重试。",
  vision_provider_call_failed: "图纸识别服务调用失败，请稍后重试。",
  coverage_blocking: "图纸识别结果不完整，请重新处理或稍后重试。",
  network_error: "网络异常，请检查连接后重试。",
  project_status_failed: "状态获取失败，请重试。",
  project_dispatch_failed: "处理服务暂时不可用，请重新处理。",
  project_intake_failed: "上传失败，请重新处理。",
  project_processing_failed: "图纸处理失败，请重新处理。",
  inventory_processing_failed: "图纸解析失败，请重新处理。",
  review_bootstrap_failed: "审核工作台准备失败，请重新处理。",
  project_workbench_unavailable: "审核工作台暂不可用，请稍后重试。",
  project_source_pdf_unavailable: "工程图纸暂不可用，请稍后重试。",
  project_not_found: "未找到该检验项目。",
  review_lock_conflict: "审核项目正由其他人员编辑，请稍后重试。",
  stale_working_copy: "审核内容已更新，请刷新后重试。",
  review_items_not_frozen: "请先冻结检验项。",
  review_not_ready: "仍有待确认内容，请完成审核后重试。",
  balloon_validation_failed: "气泡校验未通过，请先处理阻断项。",
  reviewed_result_not_found: "未找到已确认的审核结果。",
  export_in_progress: "正式文件正在生成，请稍后查看。",
  export_preflight_failed: "正式文件生成失败，请检查审核内容后重试。",
};

export const zhCN = {
  brand: "智检通",
  product: "工程图纸智能检验",
  intro: "上传工程 PDF，自动识别检验项并生成气泡图与 SIP 文件。",
  stages: [
    "上传图纸",
    "智能识别",
    "人工审核",
    "气泡调整",
    "文件导出",
  ],
  stageDescriptions: [
    "PDF文件上传",
    "识别检验项",
    "确认检验项",
    "调整气泡位置",
    "生成PDF与SIP",
  ],
  upload: {
    heading: "上传工程 PDF",
    select: "选择工程 PDF",
    submit: "上传并开始识别",
    replace: "重新选择文件",
    remove: "移除已选文件",
    retry: "重新处理",
    retryStatus: "重新获取状态",
    empty: "将工程 PDF 拖放到此处，或从本机选择文件",
    selected: "已选择文件",
    supportTitle: "支持范围",
    support: "支持包含矢量文字或可定位混合内容的工程 PDF；纯扫描 PDF 可能暂不支持。",
    safetyTitle: "文件安全",
    safety: "文件仅用于当前检验流程，不在页面展示内部标识或技术路径。",
  },
  status: {
    uploading: "正在上传工程 PDF",
    queued: "项目已创建，等待处理",
    parsing: "正在解析工程图纸",
    recognizing: "正在识别检验项",
    preparing: "正在准备审核",
    ready: "识别完成，已进入审核",
    hint: "处理完成后将自动进入审核工作台，请保持页面打开。",
  },
  recognitionPreview: {
    title: "识别预览",
    version: (revision: number) => `版本 ${revision}`,
    localReady: "本地识别完成",
    vlmEnriching: "正在进行视觉增强",
    drawingTitle: "工程图纸预览",
    localResolved: (count: number) => `本地已解析：${count}`,
    cacheResolved: (count: number) => `缓存已解析：${count}`,
    vlmPending: (count: number) => `视觉处理中：${count}`,
  },
  drawingList: {
    title: "图纸列表",
    eyebrow: "图纸任务",
    description: "继续处理已有图纸，或上传一份新的工程 PDF。",
    upload: "上传新图纸",
    empty: "还没有图纸任务",
    emptyHint: "上传第一份工程 PDF 后，可以从这里随时继续处理。",
    total: (count: number) => `共 ${count} 份图纸`,
    fileName: "图纸名称",
    status: "当前状态",
    lastOpened: "最近打开",
    action: "操作",
    continue: "继续处理",
    continueDrawing: (fileName: string) => `继续处理 ${fileName}`,
    loadingStatus: "正在获取状态",
    unavailableStatus: "状态暂不可用",
    readyStatus: "可继续审核",
    failedStatus: "处理失败",
    queuedStatus: "等待处理",
    registryWarning: "本机列表未能保存，当前图纸仍可继续处理。",
  },
  workbench: {
    loading: "正在加载审核工作台",
    title: "检验项目审核",
    eyebrow: "工程图纸检验工作台",
    stageNavigation: "检验处理阶段",
    projectSummary: "项目摘要",
    drawingRegion: "工程图纸",
    reviewRegion: "检验项审核",
    mergedReviewWorkspace: "检验项列表与编辑",
    asideRegion: "检验、导出与处理信息",
    drawingType: "图纸类型",
    drawingNumber: "图号",
    revision: "版本",
    productName: "产品名称",
    totalItems: "检验项",
    reviewedItems: "已审核",
    confirmedItems: "SIP 表格",
    currentState: "当前状态",
    saveStatus: "保存状态",
    pending: "有未保存修改",
    saving: "正在保存",
    saved: "已保存",
    saveFailed: "保存失败",
    returnToDrawingList: "回到图纸列表",
    returnDialogTitle: "返回图纸列表？",
    returnDialogDescription: "当前图纸有未保存修改，请选择如何处理。",
    saveAndReturn: "保存并返回",
    discardAndReturn: "不保存返回",
    cancelReturn: "取消",
    finishCurrentEdit: "请先保存或取消当前检验项修改",
    localReview: "待审核",
    companyLog: "公司处理记录",
    emptyCompanyLog: "暂无处理记录",
    sipInformation: "SIP 信息",
    projectSipInformation: "项目基本信息",
    selectedSipInformation: "当前检验项",
    editProjectSipInformation: "编辑项目 SIP 信息",
    recognizedMetadataSuggestion: "图纸识别，待确认",
    recognizedMetadataConsistent: "图纸识别一致",
    currentMetadataValue: (value: string) => `当前值：${value}`,
    recognizedMetadataValue: (value: string) => `图纸识别值：${value}`,
    adoptRecognizedMetadata: (label: string) => `采用识别值：${label}`,
    sipTableProgress: (ready: number, exceptions: number) =>
      `SIP 表格：已生成 ${ready}，异常 ${exceptions}`,
    sipTablePendingProgress: (pending: number) =>
      `SIP 表格：待生成 ${pending}`,
    defaultInspectionRole: "默认检验角色",
    generateSipTable: "生成并检查 SIP 表格",
    sipTableComplete: "SIP 表格已完成",
    sipTableCompleteNextStep:
      "正式文件将在审核和冻结完成后从左侧统一生成。",
    nextSipException: "处理下一条异常",
    pendingSipGeneration: "请先生成 SIP 表格，系统会自动填写可确定字段。",
    editResolvedSipRow: "查看或修改当前 SIP 行",
    sipMappingExceptions: {
      composite_method_required: "复合项需要选择检验方法",
      unsupported_item_type: "未知检验项类型",
      missing_source_page: "缺少来源页码",
      missing_inspection_role: "缺少默认检验角色",
      sip_regeneration_required: "技术要求已变更，请重新生成 SIP 表格",
    },
    confirmProjectSipInformation: "确认项目 SIP 信息",
    cancelProjectSipInformation: "取消项目 SIP 信息修改",
    selectedSourceSipUnavailable: "当前选择的是待判定来源。",
    selectItemForSip: "请选择一个有效检验项以填写 SIP 信息。",
    metadataFields: {
      materialCode: "物料编码",
      materialName: "产品名称",
      drawingNumber: "图号",
      material: "材质",
      revision: "版本号",
      unit: "单位",
      inspectionStandard: "检验标准",
      inspectionRole: "检验人员角色",
      reviewerRole: "审核人员角色",
    },
    reviewCommands: "候选项编辑与审核命令",
    unknown: "—",
    actionSubmitted: "审核修改已提交",
    itemsFrozen: "检验项已冻结",
    balloonsGenerated: "气泡已生成",
    reviewedConfirmed: "审核结果已确认",
    movingBalloon: "正在移动气泡",
    deletingBalloon: "正在删除气泡",
    rebuildingBalloon: "正在重建气泡",
    reorderingBalloon: "正在调整气泡顺序",
    renumberingBalloons: "正在重新编号",
    completed: (action: string) => `${action}完成`,
  },
  projectState: {
    editing: "审核中",
    reviewed: "审核完成",
    failed: "处理失败",
    processing: "处理中",
    queued: "等待处理",
  },
  summary: {
    region: "识别汇总",
    all: "全部",
    active: "有效项",
    excluded: "已排除",
    autoAccepted: "自动通过",
    reviewRequired: "待人工审核",
    manualRequired: "需人工处理",
    pendingSources: "待确认来源",
    hardCollision: "硬碰撞",
    filter: (label: string) => `筛选${label}`,
  },
  technicalRequirements: {
    region: "技术要求匹配",
    title: "技术要求",
    hint: "自动识别结果仅作为审核建议，确认后才进入正式 SIP。",
    count: (count: number) => `${count} 条`,
    pendingCount: (count: number) => `待确认 ${count}`,
    confirmedCount: (count: number) => `已确认 ${count}`,
    expand: "展开",
    collapse: "收起",
    expandLabel: "展开技术要求",
    collapseLabel: "收起技术要求",
    matched: (count: number) => `已匹配 ${count} 项`,
    global: "全局要求",
    pending: "待确认",
    confirmed: "已确认",
    excluded: "已排除",
    currentProcessing: "当前处理",
    decisionRequired: "需要决策",
    editing: "修改已确认结果",
    chooseMode: "选择处理方式",
    changeMode: "更改处理方式",
    useSuggestion: "应用到系统建议的检验项",
    keepCurrent: "保留当前关联项",
    suggestedTargets: (count: number) =>
      `建议覆盖 ${count} 个由规则 Owner 匹配的检验项`,
    viewSuggestion: (count: number) => `查看系统建议关联项（${count} 项）`,
    currentTargets: (count: number) => `当前关联 ${count} 个检验项`,
    useSubset: "只应用到部分检验项",
    subsetHint: "从可搜索列表中选择一个或多个检验项",
    useGlobal: "作为全局 SIP 要求",
    globalHint: "保留在 SIP 中，但不关联单个气泡",
    exclude: "排除此要求",
    excludeHint: "确认它不是本次检验范围的一部分",
    searchItems: "搜索检验项",
    noMatchingItems: "没有符合搜索条件的检验项。",
    impactTitle: "确认后会发生什么",
    matchedImpact: (count: number) =>
      `这条规则将关联到 ${count} 个检验项；对应 SIP 建议会自动预填。不会立即冻结、编号或生成气泡。`,
    globalImpact:
      "这条要求将作为无气泡的全局 SIP 要求。不会立即冻结、编号或生成气泡。",
    excludedImpact:
      "这条要求将从本次检验范围中排除，不会进入 SIP，也不会生成气泡。",
    chooseFirst: "请先选择处理方式",
    confirmAndNext: "确认并处理下一条",
    confirmEdit: "确认修改",
    cancel: "取消",
    appliedSummary: (count: number) => `已应用到 ${count} 个检验项`,
    globalSummary: "已确认为全局 SIP 要求",
    excludedSummary: "已从本次检验范围排除",
    sourcePage: (page: number) => `规则来源：图纸第 ${page} 页`,
    viewRelations: "查看关联项",
    modify: "修改",
    waiting: "等待前一条确认",
    refreshing: "已提交，正在刷新结果",
    proceed: "进入检验项审核",
    nextStepTitle: "下一步：检验项审核",
    nextStepHint:
      "检查受影响检验项中预填的 SIP 信息；技术要求确认不会直接冻结、编号或生成气泡。",
  },
  inspection: {
    region: "检验项列表",
    candidateNumber: (number: number) => `候选序号 ${number}`,
    formalNumber: (number: number) => `正式序号 ${number}`,
    noNumber: "暂无序号",
    statusFilter: "筛选状态",
    allStatuses: "全部状态",
    number: "序号",
    item: "检验项",
    value: "数值 / 公差",
    page: "页码",
    status: "状态",
    empty: "没有符合条件的检验项。",
    previousPage: "上一页",
    nextPage: "下一页",
    pageLabel: (page: number, pages: number) => `第 ${page} / ${pages} 页`,
    sourcePage: (page: number) => `第 ${page} 页`,
    selectedSip: "SIP 字段",
    inspectionItem: "检验项目",
    standard: "检验标准",
    method: "检验方法",
    keyDimension: "关键尺寸",
    role: "检验角色",
    remarks: "备注（可选）",
    confirmSip: "保存当前 SIP 字段",
    cancelSip: "取消当前 SIP 字段修改",
    statusPending: "待人工审核",
    statusBalloonPending: "待选择气泡",
    statusAutoAccepted: "自动通过",
    autoAcceptedCandidateNumber: (number: number) =>
      `自动通过气泡 ${number}`,
    statusConfirmed: "已确认",
    statusCandidate: "候选项",
    statusExcluded: "已排除",
    statusManual: "需人工处理",
    statusCollision: "硬碰撞",
    sourceType: "原始来源",
    sourcePending: "待判定来源",
    sourceEditor: "待判定来源处理",
    sourceEditorHint: "补全来源信息，并选择是否纳入检验清单",
    sourceRawText: "原始标注",
    sourceItemType: "检验类型",
    sourceScope: "范围",
    sourceBalloonRequired: "需要气泡",
    sourceBalloonHint: "纳入后同步生成气泡",
    promoteSourceWithBalloon: "添加并生成气泡",
    promoteSourceWithoutBalloon: "仅添加检验项",
    ignoreSource: "忽略，不作为检验项",
    selectItemType: "请选择检验类型",
    pagination: "检验项分页",
    types: {
      linear_dimension: "线性尺寸",
      diameter_dimension: "直径尺寸",
      thread: "螺纹",
      radius: "半径",
      angle: "角度",
      general_requirement: "通用要求",
      composite: "复合标注",
    },
    collisions: {
      protected_overlap: "存在保护区重叠",
      circle_overlap: "存在气泡重叠",
      leader_overlap: "存在引线重叠",
      page_boundary: "超出图纸边界",
    },
  },
  review: {
    region: "审核命令",
    title: "检验项目",
    keep: "保留",
    exclude: "排除",
    edit: "修改",
    cancelEdit: "取消修改",
    saveEdit: "保存修改",
    accept: "确认候选项",
    reject: "拒绝候选项",
    requireBalloon: "设为需要气泡",
    noBalloon: "设为无需气泡",
    decisionGroup: "检验结论",
    contentGroup: "内容调整",
    balloonGroup: "气泡标记",
    excludeHelp: "不进入 SIP，也不生成气泡",
    noBalloonHelp: "仍进入 SIP，仅不生成图纸气泡",
    actionGuideTitle: "怎么选择？",
    actionGuideIntro: "先判断这条内容是否仍是有效检验要求。",
    noBalloonGuide:
      "仍是有效检验要求，需要进入 SIP；仅不在图纸上生成气泡。常见于整体要求、通用标准、材质或表面处理等没有唯一标注位置的要求。",
    excludeGuide:
      "不是有效检验要求，不进入 SIP，也不生成气泡。常见于 OCR 误识别、图框或标题文字、无效重复项以及无需检验的内容。",
    excludeConfirmTitle: "确认排除这条检验项？",
    excludeConfirmDescription:
      "排除后不会进入正式 SIP，也不会生成图纸气泡。原始识别记录仍保留。",
    cancelExclude: "取消排除",
    confirmExclude: "确认排除",
    split: "拆分",
    editContent: "修改内容",
    inspectionContent: "检验内容",
    parsedResult: "解析结果",
    rawText: "原始标注",
    splitParts: "拆分内容",
    manualItem: "新增检验项",
    coordinates: "坐标",
    scope: "范围",
    type: "类型",
    localFeature: "局部特征",
    globalRequirement: "全局要求",
    addItem: "新增检验项",
    cancelManualItem: "取消新增检验项",
    balloonRequired: "需要气泡",
    unspecified: "未指定",
    yes: "是",
    no: "否",
    fields: {
      quantity: "数量",
      nominal: "基本尺寸",
      upperTolerance: "上公差",
      lowerTolerance: "下公差",
      diameter: "直径",
      featureKind: "特征类型",
      depth: "深度",
      through: "通孔",
      threadSpec: "螺纹规格",
      threadDepth: "螺纹深度",
      radius: "半径",
      angle: "角度",
    },
    types: {
      linear_dimension: "线性尺寸",
      diameter_dimension: "直径尺寸",
      thread: "螺纹",
      radius: "半径",
      angle: "角度",
      general_requirement: "通用要求",
      composite: "复合标注",
    },
    featureKinds: {
      hole: "孔",
      shaft: "轴",
      cylindrical_feature: "圆柱特征",
      unknown: "未知",
    },
    coarseTypes: {
      geometric_tolerance: "几何公差",
      roughness: "粗糙度",
      weld: "焊接",
      cross_view_duplicate: "跨视图重复",
    },
    itemIndex: (index: number) => `检验项 ${index}`,
    itemHeading: (number: number | undefined, type: string) =>
      `检验项 ${number ?? zhCN.workbench.unknown} · ${type}`,
    formalBalloonNumber: (number: number) => `气泡 ${number}`,
    fieldForItem: (field: string, rawText: string) => `${field}：${rawText}`,
    actionForItem: (action: string, rawText: string) =>
      `${action}检验项：${rawText}`,
    splitPlaceholder: "第一部分|第二部分",
    manualRawText: "新增检验项原始标注",
    manualCoordinates: "新增检验项坐标",
    manualScope: "新增检验项范围",
    manualType: "新增检验项类型",
    manualBalloonRequired: "新增检验项需要气泡",
    manualCoordinatesPlaceholder: "例如：10, 20, 30, 40",
    selectItemHint: "请先从检验项列表选择一项。",
  },
  balloon: {
    commands: "气泡操作",
    active: "个有效气泡",
    delete: "删除气泡",
    rebuild: "重建气泡",
    earlier: "编号顺序前移",
    later: "编号顺序后移",
    renumber: "重新编号",
    freeze: "冻结检验项",
    generate: "生成气泡",
    confirm: "确认审核结果",
    finalization: "审核定稿操作",
    marker: (number: number, blocked: boolean) =>
      `正式气泡 ${number}${blocked ? "，需人工处理" : ""}`,
  },
  pdf: {
    workspace: "PDF 审核工作区",
    controls: "PDF 控件",
    previous: "上一页",
    next: "下一页",
    zoomOut: "缩小",
    zoomIn: "放大",
    zoomLevel: "缩放比例",
    panLeft: "向左平移",
    panRight: "向右平移",
    panUp: "向上平移",
    panDown: "向下平移",
    fit: "适合页面",
    expandAuxiliary: "展开检验、导出与处理信息",
    collapseAuxiliary: "收起检验、导出与处理信息",
    expand: "展开工作区",
    collapse: "收起工作区",
    renderFailed: "PDF 页面渲染失败，请切换页面后重试。",
    overlay: "工程图纸标注层",
    candidateMarker: (number: number) => `候选气泡 ${number}`,
    autoAcceptedMarker: (number: number) =>
      `自动通过气泡 ${number}`,
    legend: "图纸标注图例",
    pages: "图纸页面",
    viewPage: (page: number) => `查看第 ${page} 页`,
    thumbnailUnavailable: (page: number) => `第 ${page} 页预览不可用`,
    formalBalloon: "正式气泡",
    autoAcceptedPendingNumber: "自动通过",
    candidate: "候选项",
    source: "来源标注",
    excluded: "已排除",
  },
  export: {
    region: "正式文件导出",
    title: "正式文件",
    action: "生成正式文件",
    notReviewed: "尚未审核",
    sipPending: (count: number) => `SIP 待生成 ${count} 项`,
    sipExceptions: (count: number) => `SIP 异常 ${count} 项`,
    pendingProjectSip: "项目 SIP 信息未确认",
    blocked: "存在气泡阻断项",
    ready: "待生成",
    running: "正在生成",
    failed: "生成失败",
    available: "可下载",
    published: "已发布",
    atomicHint: "带气泡 PDF、SIP Excel 与校验清单将原子发布。",
    downloadRegion: "正式文件下载",
    downloads: {
      ballooned_pdf: "下载带气泡 PDF",
      sip_excel: "下载 SIP Excel",
      manifest: "下载校验清单",
    },
    artifacts: {
      ballooned_pdf: "带气泡 PDF",
      sip_excel: "SIP Excel",
      manifest: "校验清单",
    },
  },
  errors: {
    fallback: "操作失败，请重试。",
    fatal: "处理失败，请重新选择 PDF。",
    lockRenewal: "审核锁续期失败，修改操作已暂停。",
  },
} as const;

export function apiErrorCopy(code: string): string {
  return ERROR_COPY[code] ?? zhCN.errors.fallback;
}

export function projectErrorCopy(code: string): string {
  return ERROR_COPY[code] ?? zhCN.errors.fatal;
}

export function projectErrorGuidance(code: string, retryable: boolean): string {
  if (code === "invalid_pdf" || code === "unsupported_input") {
    return "未生成正式检验结果，请重新选择符合支持范围的工程 PDF。";
  }
  if (retryable) {
    return "未生成正式检验结果，请重新处理或选择其他文件。";
  }
  return "未生成正式检验结果，请重新选择 PDF；若文件有效，请联系管理员检查服务配置。";
}

export function projectStateCopy(state?: string): string {
  if (state === undefined) return zhCN.workbench.localReview;
  return zhCN.projectState[state as keyof typeof zhCN.projectState]
    ?? zhCN.workbench.unknown;
}
