const ERROR_COPY: Readonly<Record<string, string>> = {
  invalid_pdf: "PDF 格式错误，请选择有效的工程 PDF。",
  unsupported_input: "当前 PDF 暂不支持。",
  storage_unavailable: "文件存储服务暂不可用，请稍后重试。",
  redis_unavailable: "处理协调服务暂不可用，请稍后重试。",
  celery_worker_unavailable: "图纸处理服务暂不可用，请稍后重试。",
  ocr_provider_unavailable: "文字识别服务暂不可用，请稍后重试。",
  vision_provider_unavailable: "图纸识别服务暂不可用，请稍后重试。",
  coverage_blocking: "图纸识别结果不完整，请重新处理或稍后重试。",
  network_error: "网络异常，请检查连接后重试。",
  project_status_failed: "状态获取失败，请重试。",
  project_dispatch_failed: "处理服务暂时不可用，请重新处理。",
  project_intake_failed: "上传失败，请重新处理。",
  project_processing_failed: "图纸处理失败，请重新处理。",
  inventory_processing_failed: "图纸解析失败，请重新处理。",
  review_bootstrap_failed: "审核工作台准备失败，请重新处理。",
  project_workbench_unavailable: "审核工作台暂不可用，请稍后重试。",
  project_source_pdf_unavailable: "工程图纸暂不可用，请稍后重试。",
  project_not_found: "未找到该检验项目。",
  review_lock_conflict: "审核项目正由其他人员编辑，请稍后重试。",
  stale_working_copy: "审核内容已更新，请刷新后重试。",
  review_items_not_frozen: "请先冻结检验项。",
  review_not_ready: "仍有待确认内容，请完成审核后重试。",
  balloon_validation_failed: "气泡校验未通过，请先处理阻断项。",
  reviewed_result_not_found: "未找到已确认的审核结果。",
  export_in_progress: "正式文件正在生成，请稍后查看。",
  export_preflight_failed: "正式文件生成失败，请检查审核内容后重试。",
};

export const zhCN = {
  brand: "智检通",
  product: "工程图纸智能检验",
  intro: "上传工程 PDF，自动识别检验项并生成气泡图与 SIP 文件。",
  stages: [
    "上传图纸",
    "智能识别",
    "人工审核",
    "气泡调整",
    "文件导出",
  ],
  upload: {
    heading: "上传工程 PDF",
    select: "选择工程 PDF",
    submit: "上传并开始识别",
    replace: "重新选择文件",
    retry: "重新处理",
    retryStatus: "重新获取状态",
    another: "处理另一份图纸",
    empty: "将工程 PDF 拖放到此处，或从本机选择文件",
    selected: "已选择文件",
    supportTitle: "支持范围",
    support: "支持包含矢量文字或可定位混合内容的工程 PDF；纯扫描 PDF 可能暂不支持。",
    safetyTitle: "文件安全",
    safety: "文件仅用于当前检验流程，不在页面展示内部标识或技术路径。",
  },
  status: {
    uploading: "正在上传工程 PDF",
    queued: "项目已创建，等待处理",
    processing: "正在解析图纸并识别检验项",
    preparing: "正在准备审核",
    ready: "识别完成，已进入审核",
    hint: "处理完成后将自动进入审核工作台，请保持页面打开。",
  },
  workbench: {
    loading: "正在加载审核工作台",
    title: "检验项目审核",
    eyebrow: "工程图纸检验工作台",
    stageNavigation: "检验处理阶段",
    projectSummary: "项目摘要",
    drawingRegion: "工程图纸",
    reviewRegion: "检验项审核",
    asideRegion: "SIP 与导出信息",
    drawingType: "图纸类型",
    drawingNumber: "图号",
    revision: "版本",
    productName: "产品名称",
    totalItems: "检验项",
    reviewedItems: "已审核",
    confirmedItems: "已确认",
    currentState: "当前状态",
    saveStatus: "保存状态",
    save: "保存审核修改",
    pending: "有未保存修改",
    saving: "正在保存",
    saved: "已保存",
    saveFailed: "保存失败",
    localReview: "待审核",
    companyLog: "公司处理记录",
    emptyCompanyLog: "暂无处理记录",
    metadata: "SIP基本信息",
    metadataFields: {
      materialCode: "物料编码",
      materialName: "产品名称",
      drawingNumber: "图号",
      material: "材质",
      revision: "版本号",
      unit: "单位",
      inspectionStandard: "检验标准",
      inspectionRole: "检验人员角色",
      reviewerRole: "审核人员角色",
    },
    editMetadata: "编辑 SIP 信息",
    confirmMetadata: "确认 SIP 信息",
    reviewCommands: "候选项编辑与审核命令",
    unknown: "—",
    actionSubmitted: "审核修改已提交",
    itemsFrozen: "检验项已冻结",
    balloonsGenerated: "气泡已生成",
    reviewedConfirmed: "审核结果已确认",
    movingBalloon: "正在移动气泡",
    deletingBalloon: "正在删除气泡",
    rebuildingBalloon: "正在重建气泡",
    reorderingBalloon: "正在调整气泡顺序",
    renumberingBalloons: "正在重新编号",
    completed: (action: string) => `${action}完成`,
  },
  projectState: {
    editing: "审核中",
    reviewed: "审核完成",
    failed: "处理失败",
    processing: "处理中",
    queued: "等待处理",
  },
  summary: {
    region: "识别汇总",
    all: "全部",
    active: "有效项",
    excluded: "已排除",
    manualRequired: "需人工处理",
    hardCollision: "硬碰撞",
    filter: (label: string) => `筛选${label}`,
  },
  inspection: {
    region: "检验项列表",
    selectedItemSummary: "所选检验项",
    balloonNumber: "气泡编号",
    candidateNumber: (number: number) => `候选序号 ${number}`,
    search: "搜索检验项",
    statusFilter: "筛选状态",
    allStatuses: "全部状态",
    number: "序号",
    item: "检验项",
    value: "数值 / 公差",
    page: "页码",
    status: "状态",
    empty: "没有符合条件的检验项。",
    previousPage: "上一页",
    nextPage: "下一页",
    pageLabel: (page: number, pages: number) => `第 ${page} / ${pages} 页`,
    sourcePage: (page: number) => `第 ${page} 页`,
    selectedSip: "所选检验项 SIP 确认",
    inspectionItem: "检验项目",
    standard: "检验标准",
    method: "检验方法",
    keyDimension: "关键尺寸",
    role: "检验角色",
    confirmSip: "确认所选 SIP 字段",
    statusPending: "待审核",
    statusConfirmed: "已确认",
    statusCandidate: "候选项",
    statusExcluded: "已排除",
    statusManual: "需人工处理",
    statusCollision: "硬碰撞",
    pagination: "检验项分页",
    types: {
      linear_dimension: "线性尺寸",
      diameter_dimension: "直径尺寸",
      thread: "螺纹",
      radius: "半径",
      angle: "角度",
      general_requirement: "通用要求",
      composite: "复合标注",
    },
    collisions: {
      protected_overlap: "存在保护区重叠",
      circle_overlap: "存在气泡重叠",
      leader_overlap: "存在引线重叠",
      page_boundary: "超出图纸边界",
    },
  },
  review: {
    region: "审核命令",
    title: "检验项目",
    keep: "保留",
    exclude: "排除",
    edit: "修改",
    accept: "确认候选项",
    reject: "拒绝候选项",
    requireBalloon: "设为需要气泡",
    noBalloon: "设为无需气泡",
    split: "拆分",
    merge: "合并所选检验项",
    rawText: "原始标注",
    splitParts: "拆分内容",
    manualItem: "新增检验项",
    coordinates: "坐标",
    scope: "范围",
    type: "类型",
    localFeature: "局部特征",
    globalRequirement: "全局要求",
    addItem: "新增检验项",
    balloonRequired: "需要气泡",
    requiresConfirmation: "需要人工确认",
    complexFields: "复杂检验项字段",
    coarseType: "粗分类",
    unspecified: "未指定",
    yes: "是",
    no: "否",
    fields: {
      quantity: "数量",
      nominal: "基本尺寸",
      upperTolerance: "上公差",
      lowerTolerance: "下公差",
      diameter: "直径",
      featureKind: "特征类型",
      depth: "深度",
      through: "通孔",
      threadSpec: "螺纹规格",
      threadDepth: "螺纹深度",
      radius: "半径",
      angle: "角度",
    },
    types: {
      linear_dimension: "线性尺寸",
      diameter_dimension: "直径尺寸",
      thread: "螺纹",
      radius: "半径",
      angle: "角度",
      general_requirement: "通用要求",
      composite: "复合标注",
    },
    featureKinds: {
      hole: "孔",
      shaft: "轴",
      cylindrical_feature: "圆柱特征",
      unknown: "未知",
    },
    coarseTypes: {
      geometric_tolerance: "几何公差",
      roughness: "粗糙度",
      weld: "焊接",
      cross_view_duplicate: "跨视图重复",
    },
    itemIndex: (index: number) => `检验项 ${index}`,
    selectItem: (index: number, rawText: string) =>
      `选择检验项 ${index}：${rawText}`,
    fieldForItem: (field: string, rawText: string) => `${field}：${rawText}`,
    actionForItem: (action: string, rawText: string) =>
      `${action}检验项：${rawText}`,
    splitPlaceholder: "第一部分|第二部分",
    manualRawText: "新增检验项原始标注",
    manualCoordinates: "新增检验项坐标",
    manualScope: "新增检验项范围",
    manualType: "新增检验项类型",
    manualBalloonRequired: "新增检验项需要气泡",
    manualCoordinatesPlaceholder: "例如：10, 20, 30, 40",
    mergeSelection: "选择需要合并的检验项",
    selectItemHint: "请先从检验项列表选择一项。",
  },
  coverageReview: {
    region: "来源待确认",
    title: "来源待确认",
    hint: "请核对图纸中的原始来源，再确认是否保留。",
    progress: (current: number, total: number) => `${current} / ${total}`,
    rawText: "原始标注",
    sourcePage: "来源页码",
    previous: "上一条来源",
    next: "下一条来源",
    accept: "确认保留此来源",
    reject: "确认忽略此来源",
  },
  balloon: {
    commands: "气泡操作",
    active: "个有效气泡",
    delete: "删除气泡",
    rebuild: "重建气泡",
    earlier: "气泡前移",
    later: "气泡后移",
    renumber: "重新编号",
    freeze: "冻结检验项",
    generate: "生成气泡",
    confirm: "确认审核结果",
    finalization: "审核定稿操作",
    marker: (number: number, blocked: boolean) =>
      `气泡 ${number}${blocked ? "，需人工处理" : ""}`,
  },
  pdf: {
    workspace: "PDF 审核工作区",
    controls: "PDF 控件",
    previous: "上一页",
    next: "下一页",
    zoomOut: "缩小",
    zoomIn: "放大",
    zoomLevel: "缩放比例",
    panLeft: "向左平移",
    panRight: "向右平移",
    panUp: "向上平移",
    panDown: "向下平移",
    fit: "适合页面",
    expand: "展开工作区",
    collapse: "收起工作区",
    renderFailed: "PDF 页面渲染失败，请切换页面后重试。",
    overlay: "工程图纸标注层",
    candidateMarker: (number: number) => `候选气泡 ${number}`,
    legend: "图纸标注图例",
    pages: "图纸页面",
    viewPage: (page: number) => `查看第 ${page} 页`,
    formalBalloon: "正式气泡",
    candidate: "候选项",
    source: "来源标注",
    excluded: "已排除",
  },
  export: {
    region: "正式文件导出",
    title: "正式文件",
    action: "生成正式文件",
    notReviewed: "尚未审核",
    blocked: "存在气泡阻断项",
    ready: "待生成",
    running: "正在生成",
    failed: "生成失败",
    available: "可下载",
    published: "已发布",
    atomicHint: "带气泡 PDF、SIP Excel 与校验清单将原子发布。",
    downloadRegion: "正式文件下载",
    downloads: {
      ballooned_pdf: "下载带气泡 PDF",
      sip_excel: "下载 SIP Excel",
      manifest: "下载校验清单",
    },
    artifacts: {
      ballooned_pdf: "带气泡 PDF",
      sip_excel: "SIP Excel",
      manifest: "校验清单",
    },
  },
  errors: {
    fallback: "操作失败，请重试。",
    fatal: "处理失败，请重新选择 PDF。",
    lockRenewal: "审核锁续期失败，修改操作已暂停。",
  },
} as const;

export function apiErrorCopy(code: string): string {
  return ERROR_COPY[code] ?? zhCN.errors.fallback;
}

export function projectErrorCopy(code: string): string {
  return ERROR_COPY[code] ?? zhCN.errors.fatal;
}

export function projectStateCopy(state?: string): string {
  if (state === undefined) return zhCN.workbench.localReview;
  return zhCN.projectState[state as keyof typeof zhCN.projectState]
    ?? zhCN.workbench.unknown;
}
