#!/usr/bin/env python3
"""Validate schemas, P0 classifications, generated bytes, and typed bindings."""

from __future__ import annotations

import copy
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator, FormatChecker
import yaml


ROOT = Path(__file__).resolve().parents[3]
HARNESS = ROOT / ".agent/harness"
TRACE = ROOT / "docs/superpowers/plans/2026-07-21-p0-contract-traceability-matrix.md"
GLOBAL = ROOT / "docs/contracts/MAIN_CONTRACT_MATRIX.md"
MIRROR_PATH = HARNESS / "contracts/p0-contracts.json"
BINDINGS_PATH = HARNESS / "contracts/global-contract-bindings.json"
FAILURE_SEVERITY_POLICY_PATH = HARNESS / "policy/failure-severity-policy.yaml"
SCHEMAS = HARNESS / "schemas"
EXPECTED_SCHEMA_FILES = (
    "contract-result.schema.json",
    "current-four-manifest.schema.json",
    "global-contract-bindings.schema.json",
    "human-verdict.schema.json",
    "live-run-evidence.schema.json",
    "p0-contracts.schema.json",
    "provider-fixture.schema.json",
    "receipt.schema.json",
    "run.schema.json",
    "symbol-routing-canary-evidence.schema.json",
    "visual-symbol-annotation-verdict.schema.json",
    "visual-symbol-eval.schema.json",
)

GLOBAL_ID_RE = re.compile(r"^[A-Z]+-[0-9]{3}$")
DEFINITION_COLUMNS = (
    "p0_contract_id",
    "global_contract_id",
    "implementation_only",
    "related_global_contract_ids",
    "stable_p0_requirement",
    "owner",
    "task_id",
    "tier",
    "verification_selector",
    "blocking_level",
    "implementation_reason",
)
RESULT_STATES = ("passed", "failed", "blocked", "not_run")
BUCKETS = (
    "primary_p0_contract_ids",
    "related_business_p0_contract_ids",
    "related_implementation_p0_contract_ids",
)


class ContractCheckError(RuntimeError):
    """A deterministic contract check failed."""


def _load_json(path: Path) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ContractCheckError(f"missing required file: {path.relative_to(ROOT)}") from exc
    except json.JSONDecodeError as exc:
        raise ContractCheckError(f"invalid JSON in {path.relative_to(ROOT)}: {exc}") from exc


def _schema_errors(schema: dict[str, Any], instance: Any) -> list[str]:
    validator = Draft202012Validator(schema, format_checker=FormatChecker())
    errors = sorted(
        validator.iter_errors(instance),
        key=lambda error: tuple(str(part) for part in error.absolute_path),
    )
    messages: list[str] = []
    for error in errors:
        location = "/".join(str(part) for part in error.absolute_path) or "<root>"
        messages.append(f"{location}: {error.message}")
    return messages


def _validate_schemas_and_instances() -> tuple[dict[str, Any], dict[str, Any]]:
    schema_paths = sorted(SCHEMAS.glob("*.schema.json"))
    actual_schema_files = tuple(path.name for path in schema_paths)
    if actual_schema_files != EXPECTED_SCHEMA_FILES:
        raise ContractCheckError(
            "JSON Schema inventory mismatch: "
            f"expected {list(EXPECTED_SCHEMA_FILES)}, found {list(actual_schema_files)}"
        )
    schemas: dict[str, dict[str, Any]] = {}
    for path in schema_paths:
        schema = _load_json(path)
        try:
            Draft202012Validator.check_schema(schema)
        except Exception as exc:  # jsonschema exposes several schema-error subclasses
            raise ContractCheckError(f"invalid schema {path.name}: {exc}") from exc
        schemas[path.name] = schema

    mirror = _load_json(MIRROR_PATH)
    bindings = _load_json(BINDINGS_PATH)
    for name, instance in (
        ("p0-contracts.schema.json", mirror),
        ("global-contract-bindings.schema.json", bindings),
    ):
        errors = _schema_errors(schemas[name], instance)
        if errors:
            raise ContractCheckError(f"{name} validation failed: {'; '.join(errors)}")
    return mirror, bindings


def _table_cells(line: str) -> list[str]:
    stripped = line.strip()
    return [cell.strip() for cell in stripped[1:-1].split("|")]


def _strip_outer_code(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value.startswith("`") and value.endswith("`"):
        return value[1:-1].strip()
    return value


def _global_contracts() -> dict[str, str]:
    contracts: dict[str, str] = {}
    for line in GLOBAL.read_text(encoding="utf-8").splitlines():
        if not line.lstrip().startswith("|") or not line.rstrip().endswith("|"):
            continue
        cells = _table_cells(line)
        if len(cells) != 11:
            continue
        contract_id = _strip_outer_code(cells[0])
        if not GLOBAL_ID_RE.fullmatch(contract_id):
            continue
        if contract_id in contracts:
            raise ContractCheckError(f"duplicate global contract ID: {contract_id}")
        contracts[contract_id] = _strip_outer_code(cells[10])
    return contracts


def _canonical_digest(value: Any) -> str:
    encoded = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _definition_hash(contracts: list[dict[str, Any]]) -> str:
    return _canonical_digest(
        [{key: row[key] for key in DEFINITION_COLUMNS} for row in contracts]
    )


def _status_hash(contracts: list[dict[str, Any]]) -> str:
    return _canonical_digest(
        [
            {
                "p0_contract_id": row["p0_contract_id"],
                "current_status": row["current_status"],
            }
            for row in contracts
        ]
    )


def _require_exact_generated_bytes(script_name: str, label: str) -> None:
    result = subprocess.run(
        [sys.executable, str(HARNESS / "scripts" / script_name), "--check"],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        detail = (result.stdout + result.stderr).strip()
        raise ContractCheckError(f"{label} drift: {detail or 'generated bytes differ'}")


def _binding_conflicts(bindings: list[dict[str, Any]]) -> int:
    conflicts = 0
    for binding in bindings:
        typed = [set(binding[name]) for name in BUCKETS]
        conflicts += len((typed[0] & typed[1]) | (typed[0] & typed[2]) | (typed[1] & typed[2]))
        for name in BUCKETS:
            values = binding[name]
            if values != sorted(set(values)):
                raise ContractCheckError(
                    f"{binding['global_contract_id']}: {name} is not sorted and unique"
                )
    return conflicts


def _failure_proof_selector_drift(contracts: list[dict[str, Any]]) -> int:
    try:
        policy = yaml.safe_load(
            FAILURE_SEVERITY_POLICY_PATH.read_text(encoding="utf-8")
        )
    except yaml.YAMLError as exc:
        raise ContractCheckError(
            "failure severity policy is invalid YAML"
        ) from exc
    proof = policy.get("failure_proof") if isinstance(policy, dict) else None
    if not isinstance(proof, dict):
        raise ContractCheckError("failure severity policy is missing failure_proof")
    contract_id = proof.get("contract_id")
    selector = proof.get("selector")
    matches = [
        row["verification_selector"]
        for row in contracts
        if row["p0_contract_id"] == contract_id
    ]
    if len(matches) != 1 or selector != matches[0]:
        raise ContractCheckError(
            "failure proof selector drift: "
            f"policy={selector!r} contract={matches[0] if len(matches) == 1 else None!r}"
        )
    return 0


def check() -> dict[str, int]:
    # 1. Validate all Draft 2020-12 schemas, then the two generated instances.
    mirror, bindings_document = _validate_schemas_and_instances()
    contracts = mirror["contracts"]
    global_contracts = _global_contracts()
    if len(global_contracts) != 69:
        raise ContractCheckError(f"expected 69 global contracts, found {len(global_contracts)}")

    # 2. Validate the P0 row count and ID uniqueness.
    p0_ids = [row["p0_contract_id"] for row in contracts]
    duplicate = len(p0_ids) - len(set(p0_ids))
    if len(contracts) != 111 or duplicate:
        raise ContractCheckError(
            f"expected 111 unique P0 IDs, found rows={len(contracts)} duplicate={duplicate}"
        )

    # 3. Preserve the exact business/implementation classification boundary.
    mapped = sum(
        not row["implementation_only"] and row["global_contract_id"] is not None
        for row in contracts
    )
    implementation_only = sum(
        row["implementation_only"] and row["global_contract_id"] is None
        for row in contracts
    )
    unclassified = len(contracts) - mapped - implementation_only
    if (mapped, implementation_only, unclassified) != (101, 10, 0):
        raise ContractCheckError(
            "classification mismatch: "
            f"mapped={mapped} implementation_only={implementation_only} "
            f"unclassified={unclassified}"
        )

    # 4. Validate all primary/related global IDs and implementation reasons.
    referenced: set[str] = set()
    for row in contracts:
        primary = row["global_contract_id"]
        if primary is not None:
            referenced.add(primary)
        referenced.update(row["related_global_contract_ids"])
        reason = row["implementation_reason"].strip()
        if not reason:
            raise ContractCheckError(f"{row['p0_contract_id']}: empty implementation reason")
        if row["implementation_only"] and reason == "—":
            raise ContractCheckError(
                f"{row['p0_contract_id']}: implementation-only reason is not classified"
            )
    unknown = sorted(referenced - set(global_contracts))
    if unknown:
        raise ContractCheckError(f"unknown global contract IDs: {', '.join(unknown)}")

    # 5. Validate executable selection metadata and current result projection.
    required_non_empty = (
        "task_id",
        "tier",
        "verification_selector",
        "blocking_level",
        "current_status",
    )
    for row in contracts:
        for field in required_non_empty:
            value = row[field]
            if not isinstance(value, str) or not value.strip():
                raise ContractCheckError(f"{row['p0_contract_id']}: empty {field}")
    missing_task = sum(not row["task_id"].strip() for row in contracts)
    missing_selector = sum(not row["verification_selector"].strip() for row in contracts)
    failure_proof_selector_drift = _failure_proof_selector_drift(contracts)

    # Definition/status digests are checked before byte drift for actionable errors.
    if mirror["contract_definition_hash"] != _definition_hash(contracts):
        raise ContractCheckError("contract_definition_hash does not match all definition columns")
    if mirror["status_projection_hash"] != _status_hash(contracts):
        raise ContractCheckError("status_projection_hash does not match current_status projection")

    # 6. Regenerate Markdown -> mirror in memory and compare exact bytes without writing.
    _require_exact_generated_bytes("generate-contract-mirror.py", "mirror")
    mirror_drift = 0

    # 7. Regenerate mirror -> bindings in memory and compare exact bytes without writing.
    _require_exact_generated_bytes("generate-global-bindings.py", "bindings")
    bindings_drift = 0

    # 8. A P0 task must not select or relate a P1/P2 global row.
    excluded = sorted(
        global_id
        for global_id in referenced
        if global_contracts[global_id] in {"P1", "P2"}
    )
    if excluded:
        raise ContractCheckError(
            f"P1/P2 global contracts selected or related into P0: {', '.join(excluded)}"
        )

    # 9. Keep direct and typed-related coverage distinct for every P0 boundary row.
    bindings = bindings_document["bindings"]
    binding_relation_conflict = _binding_conflicts(bindings)
    if binding_relation_conflict:
        raise ContractCheckError(
            f"binding relation conflicts: {binding_relation_conflict}"
        )
    bound_global_ids = {
        binding["global_contract_id"]
        for binding in bindings
        if any(binding[name] for name in BUCKETS)
    }
    required_global_ids = {
        global_id
        for global_id, stage in global_contracts.items()
        if stage in {"P0", "P0-partial"}
    }
    unbound = sorted(required_global_ids - bound_global_ids)
    if unbound:
        raise ContractCheckError(
            f"unbound P0/P0-partial global contracts: {', '.join(unbound)}"
        )

    changed = copy.deepcopy(contracts)
    current = changed[0]["current_status"]
    changed[0]["current_status"] = next(state for state in RESULT_STATES if state != current)
    definition_hash_stable = int(
        _definition_hash(changed) == _definition_hash(contracts)
        and _status_hash(changed) != _status_hash(contracts)
    )
    if not definition_hash_stable:
        raise ContractCheckError("definition hash is not stable under a status-only change")

    return {
        "global_contracts": len(global_contracts),
        "p0_contracts": len(contracts),
        "mapped": mapped,
        "implementation_only": implementation_only,
        "unclassified": unclassified,
        "duplicate": duplicate,
        "missing_task": missing_task,
        "missing_selector": missing_selector,
        "failure_proof_selector_drift": failure_proof_selector_drift,
        "mirror_drift": mirror_drift,
        "bindings_drift": bindings_drift,
        "unbound_p0_stage_global": len(unbound),
        "binding_relation_conflict": binding_relation_conflict,
        "definition_hash_stable_under_status_only_change": definition_hash_stable,
    }


def main() -> int:
    try:
        metrics = check()
    except (ContractCheckError, OSError, KeyError, TypeError, ValueError) as exc:
        print(f"contract check failed: {exc}", file=sys.stderr)
        return 1
    for name, value in metrics.items():
        print(f"{name}={value}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
