#!/usr/bin/env python3
"""Generate typed global-to-P0 bindings from the executable mirror only."""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
MIRROR = ROOT / ".agent/harness/contracts/p0-contracts.json"
OUTPUT = ROOT / ".agent/harness/contracts/global-contract-bindings.json"
MIRROR_SOURCE = str(MIRROR.relative_to(ROOT))

BUCKETS = (
    "primary_p0_contract_ids",
    "related_business_p0_contract_ids",
    "related_implementation_p0_contract_ids",
)


def build_bindings(mirror: dict[str, Any]) -> dict[str, Any]:
    by_global: dict[str, dict[str, set[str]]] = {}

    def bucket(global_id: str) -> dict[str, set[str]]:
        return by_global.setdefault(
            global_id,
            {name: set() for name in BUCKETS},
        )

    for row in mirror["contracts"]:
        p0_id = row["p0_contract_id"]
        if row["implementation_only"]:
            if row["global_contract_id"] is not None:
                raise ValueError(f"{p0_id}: implementation-only row has a primary global ID")
            related_bucket = "related_implementation_p0_contract_ids"
        else:
            global_id = row["global_contract_id"]
            if global_id is None:
                raise ValueError(f"{p0_id}: business row is missing a primary global ID")
            bucket(global_id)["primary_p0_contract_ids"].add(p0_id)
            related_bucket = "related_business_p0_contract_ids"

        for related_id in row["related_global_contract_ids"]:
            bucket(related_id)[related_bucket].add(p0_id)

    bindings: list[dict[str, Any]] = []
    for global_id, typed in sorted(by_global.items()):
        overlaps = (
            (typed[BUCKETS[0]] & typed[BUCKETS[1]])
            | (typed[BUCKETS[0]] & typed[BUCKETS[2]])
            | (typed[BUCKETS[1]] & typed[BUCKETS[2]])
        )
        if overlaps:
            raise ValueError(
                f"{global_id}: binding relation conflict for {', '.join(sorted(overlaps))}"
            )
        bindings.append(
            {
                "global_contract_id": global_id,
                **{name: sorted(typed[name]) for name in BUCKETS},
            }
        )

    return {
        "schema_version": "global-contract-bindings/1",
        "source": MIRROR_SOURCE,
        "global_source": mirror["global_source"],
        "contract_definition_hash": mirror["contract_definition_hash"],
        "bindings": bindings,
    }


def generated_bytes() -> bytes:
    mirror = json.loads(MIRROR.read_text(encoding="utf-8"))
    return (
        json.dumps(build_bindings(mirror), ensure_ascii=False, sort_keys=True, indent=2)
        + "\n"
    ).encode("utf-8")


def _atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temp_path = Path(temporary.name)
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temp_path, path)
        temp_path = None
    finally:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare exact generated bytes without writing",
    )
    args = parser.parse_args(argv)
    try:
        content = generated_bytes()
        if args.check:
            if not OUTPUT.exists() or OUTPUT.read_bytes() != content:
                print("bindings drift: regenerate global-contract-bindings.json", file=sys.stderr)
                return 1
            return 0
        _atomic_write(OUTPUT, content)
        print(f"generated={OUTPUT.relative_to(ROOT)}")
        return 0
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as exc:
        print(f"generate-global-bindings: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
